AWSTemplateFormatVersion: "2010-09-09"
Description: "Build pipeline for client tracking events microservice"
Parameters:
  TemplateUrlSSM:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /elevensoftware/build/SAMPipelineUrl
Mappings: 
  AccountMapping: 
    Reporting:
      Development: 512337418224 
      Staging: 265848155493 
      Production: 421870691823 
    Monolith:
      Development: 489354756207 
      Staging: 604057372515 
      Production: 615423619382 
Resources:
  Dev: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateUrlSSM
      Parameters:
        GithubRepository: rep-esimport-proxy
        GithubBranch: develop
        StackName: rep-esimport-proxy
        DotNetRuntime: '8.0'
        SlackEmail: ''
        CustomBuildspec: true
        DevelopmentAccount:  !FindInMap [AccountMapping, Reporting, Development]
        DeleteDevelopmentStackUponApproval: false
        ServiceGroup: rep-esimport-proxy
        Contact: reporting 
        Datadog: false
        DevelopmentParameters: |
          {
            "EventBusTopicArn": "arn:aws:sns:us-west-2:512337418224:eleven-event-bus-receive",
            "EventsBusAccount": "512337418224",
            "LogLevel": "DEBUG"
          }
    Staging: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateUrlSSM
      Parameters:
        GithubRepository: rep-esimport-proxy
        GithubBranch: next
        StackName: rep-esimport-proxy
        DotNetRuntime: '8.0'
        SlackEmail: ''
        CustomBuildspec: true
        StagingAccount:  !FindInMap [AccountMapping, Reporting, Staging]
        DeleteStagingStackUponApproval: false
        ServiceGroup: rep-esimport-proxy
        Contact: reporting 
        Datadog: false
        StagingParameters: |
          {
            "EventBusTopicArn": "arn:aws:sns:us-west-2:265848155493:eleven-event-bus-receive",
            "EventsBusAccount": "265848155493",
            "LogLevel": "DEBUG"
          }
    Production:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateUrlSSM
      Parameters:
        GithubRepository: rep-esimport-proxy
        GithubBranch: main
        StackName: rep-esimport-proxy
        DotNetRuntime: '8.0'
        SlackEmail: ''
        CustomBuildspec: true
        ProductionAccount:  !FindInMap [AccountMapping, Reporting, Production]
        DeleteProductionStackUponApproval: false
        ServiceGroup: rep-esimport-proxy
        Contact: reporting
        Datadog: false
        ProductionParameters: |
          {
            "EventBusTopicArn": "arn:aws:sns:us-west-2:421870691823:eleven-event-bus-receive",
            "EventsBusAccount": "421870691823",
            "LogLevel": "DEBUG"
          }
